// Sample product data
const products = [
    {
      id: 1,
      name: "Sencha Fukamushi",
      description: "Deep-steamed green tea with a rich, sweet flavor",
      price: 24.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Green Tea",
      origin: "Japan",
    },
    {
      id: 2,
      name: "Earl Grey Imperial",
      description: "Premium black tea with bergamot oil",
      price: 22.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Black Tea",
      origin: "India",
    },
    {
      id: 3,
      name: "Jasmine Pearl",
      description: "Hand-rolled green tea scented with jasmine blossoms",
      price: 29.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Green Tea",
      origin: "China",
    },
    {
      id: 4,
      name: "Darjeeling First Flush",
      description: "Light and floral black tea from the Himalayan foothills",
      price: 34.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Black Tea",
      origin: "India",
    },
    {
      id: 5,
      name: "Tie Guan Yin",
      description: "Premium oolong tea with orchid aroma and smooth finish",
      price: 39.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Oolong Tea",
      origin: "China",
    },
    {
      id: 6,
      name: "Chamomile Blossoms",
      description: "Soothing herbal infusion with apple-like sweetness",
      price: 18.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Herbal Tea",
      origin: "Egypt",
    },
    {
      id: 7,
      name: "Matcha Ceremonial",
      description: "Stone-ground premium green tea powder",
      price: 44.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Green Tea",
      origin: "Japan",
    },
    {
      id: 8,
      name: "Assam Gold",
      description: "Malty black tea with rich caramel notes",
      price: 26.95,
      image: "/placeholder.svg?height=400&width=400",
      category: "Black Tea",
      origin: "India",
    },
  ]
  
  